name:                automorphism-group
version:             0.0.0.0
github:              "nbloomf/automorphism-group"
license:             GPL3
author:              "Nathan Bloomfield"
maintainer:          "nbloomf@gmail.com"
copyright:           "Automattic, Inc"

extra-source-files:
- README.md
- ChangeLog.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nbloomf/automorphism-group#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  automorphism-group-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - automorphism-group

tests:
  automorphism-group-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - automorphism-group
